apiVersion: v1
kind: Pod
metadata:
  name: pod-inspector
  namespace: tasks
  labels:
    app: pod-inspector
spec:
  containers:
    - name: web
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80